### ISSUE TITLE
Goldpinger Ingress - Should move to apiVersion: networking.k8s.io/v1

### ISSUE THREAD

**Issue by matthewmrichter** [okgolove/helm-charts#46]
**Is this a request for help?**: Yes, or I can PR it if you'll let me

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature-ish / Avoid Deprecation

**Version of Helm and Kubernetes**: Helm 3. Kubernetes 1.14 +

**Which chart**: goldpinger

**What happened**: The Ingress object is using `apiVersion: extensions/v1beta1`. `extensions/v1beta1 Ingress` is deprecated in Kubernetes v1.14+, unavailable in Kubernetes v1.22+; this chart should use `networking.k8s.io/v1 Ingress`. In my use case it is breaking my integration with `aws-load-balancer-controller` which relies on `networking.k8s.io/v1 Ingress` so I can't use the upstream repo..

**What you expected to happen**: Ingress.yaml should not use a deprecated API. It should use `networking.k8s.io/v1 Ingress`

**How to reproduce it** (as minimally and precisely as possible): Deploy the chart

**Anything else we need to know**: Rules spec will need to change too, likely:

```
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  {{- end }}
```
